baseURL = 'https://xeroxxhah.github.io/blog/'
languageCode = 'en-us'
title = 'The Dark Arts'
theme = 'hello-friend-ng'

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[[menu.main]]
	identifier = "blog"
	name       = "Blog"
	Mel        = "/posts"

[[menu.main]]
	identifier = "project"
	name       = "Projects"
	url        = "/project"


[[menu.main]]
	identifier = "Me"
	name       = "About Me"
	url        = "/me"

