baseURL = 'https://xeroxxhah.github.io/blog/'
languageCode = 'en-us'
title = 'THE D4RK ARTS'
theme = 'hello-friend-ng'

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[[menu.main]]
	identifier = "post"
	name       = "Blog"
	url        = "/posts"


[[menu.main]]
	identifier = "project"
	name       = "Projects"
	url        = "/project"


[[menu.main]]
	identifier = "Me"
	name       = "About Me"
	url        = "/me"

